# pnpm workspace config — Proyecto-Final frontend
# Doc: https://pnpm.io/pnpm-workspace_yaml
packages:
  - .

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false

# Dependencias nativas autorizadas a correr build scripts
# Doc: https://pnpm.io/settings#onlybuiltdependencies
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
